### ISSUE TITLE
DBの初期化用のSQL文が消えた

### ISSUE THREAD

**Issue by Utree** [line-school2018summer/kyotob_api#13]
おそらく、.gitignoreに
"!mysql/init/init.sql"の追記が必要かと、、、

**Comment by ha1f** [comment]
https://github.com/line-school2018summer/kyotob_api/blob/master/.gitignore#L30

ありそうではある

**Comment by Utree** [comment]
たしかに。そうですね。じゃ、なんで"mysql/init/init.sql"が消えたんだろ？

**Comment by satonmp** [comment]
もともとこのリポジトリには存在していなかった可能性

**Comment by 0918nobita** [comment]
#14 修正しました
