### ISSUE TITLE
１対１のroomをつくるときにroom_nameを指定できるようにするのかを検討する

### ISSUE THREAD

**Issue by Utree** [line-school2018summer/kyotob_api#8]
もし、指定できるのであれば、APIリファレンスを更新する

**Comment by satonmp** [comment]
作成時に指定するのはAPI的にもクライアント的にも厳しいかと思います
renameは少なくともAPIについては簡単に実装できるのでそちらを検討してはどうでしょうか。

**Comment by Utree** [comment]
room_nameはroomで決め打ち
