### ISSUE TITLE
apiリファレンス（I12セル） "user_screen_name" -> "user_id"

### ISSUE THREAD

**Issue by Utree** [line-school2018summer/kyotob_api#9]
apiリファレンスの表記について

I12 "recent_message" -> "message" (これはどっちでもいい)
I12 "user_screen_name" -> "user_id" (表記名は重複を許すので表記名が同じ人同士の場合、クライアントで区別できない)

**Comment by satonmp** [comment]
>I12 "recent_message" -> "message" (これはどっちでもいい)
roomにある全てのmessageを受け取るわけなので、確かにrecentとは限らないので修正すべきだと思います。
>I12 "user_screen_name" -> "user_id" (表記名は重複を許すので表記名が同じ人同士の場合、クライアントで区別できない)
message送受信にはroom_idさえあればよいので、ここでuser_screen_nameを返しているのはあくまで表示用だと思います。ただ、UI設計を詰めて行ったわけではなくuser_nameも表示に含める可能性があることを考えると、user_nameもresponseに加えておくべきだと思います。

以上二点(I11:user_name追加 , I12:user_name追加,recent_message->messageに)修正します。

**Comment by satonmp** [comment]
> I12 "user_screen_name" -> "user_id" (表記名は重複を許すので表記名が同じ人同士の場合、クライアントで区別できない)

すみません、確かにクライアント側で少なくとも自分の発言と自分以外の発言を見分ける必要がありますね。今気づきました...
